[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 1000
# Enable viaIR
via_ir = true

ffi = true

[rpc_endpoints]
anvil = "http://localhost:8545"
sapphire_testnet = "https://testnet.sapphire.oasis.io"
sapphire_mainnet = "https://sapphire.oasis.io"
